export const states = [
  "Tamil Nadu",
  "Karnataka",
  "Kerala",
  "Andhra Pradesh",
  "Telangana",
  "Maharashtra",
  "Gujarat",
  "Rajasthan",
  "Delhi",
  "Uttar Pradesh",
  "West Bengal",
  "Punjab",
  "Haryana",
  "Madhya Pradesh",
  "Bihar",
  "Odisha",
  "Assam",
  "Jharkhand",
  "Chhattisgarh",
  "Himachal Pradesh",
  "Uttarakhand",
  "Goa",
  "Tripura",
  "Manipur",
  "Meghalaya",
  "Sikkim",
  "Nagaland",
  "Mizoram",
  "Arunachal Pradesh",
  "Jammu and Kashmir",
  "Ladakh",
];

export const districtsByState: Record<string, string[]> = {
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Tiruchirappalli",
    "Salem",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Thanjavur",
    "Kancheepuram",
    "Cuddalore",
    "Karur",
    "Pudukottai",
    "Ramanathapuram",
    "Sivaganga",
    "Virudhunagar",
    "Namakkal",
    "Dharmapuri",
    "Krishnagiri",
    "Villupuram",
    "Tiruvarur",
    "Nagapattinam",
    "Theni",
    "The Nilgiris",
    "Perambalur",
    "Ariyalur",
    "Tirupur",
    "Kallakurichi",
    "Ranipet",
    "Tirupathur",
    "Chengalpattu",
    "Tenkasi",
    "Mayiladuthurai",
  ],
  Karnataka: [
    "Bengaluru Urban",
    "Bengaluru Rural",
    "Mysuru",
    "Tumakuru",
    "Mandya",
    "Hassan",
    "Shimoga",
    "Chitradurga",
    "Davangere",
    "Ballari",
    "Koppala",
    "Raichur",
    "Kalaburagi",
    "Bidar",
    "Vijayapura",
    "Bagalkote",
    "Belagavi",
    "Dharwad",
    "Gadag",
    "Haveri",
    "Uttara Kannada",
    "Udupi",
    "Dakshina Kannada",
    "Kodagu",
    "Chamarajanagar",
    "Chikkaballapura",
    "Chikkamagaluru",
    "Kolar",
    "Yadgir",
  ],
  Kerala: [
    "Thiruvananthapuram",
    "Kollam",
    "Pathanamthitta",
    "Alappuzha",
    "Kottayam",
    "Idukki",
    "Ernakulam",
    "Thrissur",
    "Palakkad",
    "Malappuram",
    "Kozhikode",
    "Wayanad",
    "Kannur",
    "Kasaragod",
  ],
  "Andhra Pradesh": [
    "Srikakulam",
    "Vizianagaram",
    "Visakhapatnam",
    "East Godavari",
    "West Godavari",
    "Krishna",
    "Guntur",
    "Prakasam",
    "Nellore",
    "Chittoor",
    "Kadapa",
    "Anantapur",
    "Kurnool",
  ],
  Telangana: [
    "Hyderabad",
    "Secunderabad",
    "Adilabad",
    "Komaram Bheem",
    "Mancherial",
    "Nirmal",
    "Nizamabad",
    "Jagitial",
    "Rajanna Sircilla",
    "Karimnagar",
    "Peddapalli",
    "Jayashankar",
    "Mulugu",
    "Bhadradri Kothagudem",
    "Khammam",
    "Suryapet",
    "Nalgonda",
    "Rangareddy",
    "Hyderabad",
    "Medchal Malkajgiri",
    "Sangareddy",
    "Medak",
    "Kamareddy",
    "Mahabubnagar",
    "Nagarkurnool",
    "Wanaparthy",
    "Jogulamba Gadwal",
    "Vikarabad",
  ],
};
